#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate 200 English vocabulary words for kids learning app
"""

words = [
    # 水果 Fruits (15)
    ('Apple', '苹果', 'fruits', '🍎'),
    ('Banana', '香蕉', 'fruits', '🍌'),
    ('Orange', '橙子', 'fruits', '🍊'),
    ('Grape', '葡萄', 'fruits', '🍇'),
    ('Strawberry', '草莓', 'fruits', '🍓'),
    ('Peach', '桃子', 'fruits', '🍑'),
    ('Pear', '梨', 'fruits', '🍐'),
    ('Watermelon', '西瓜', 'fruits', '🍉'),
    ('Cherry', '樱桃', 'fruits', '🍒'),
    ('Lemon', '柠檬', 'fruits', '🍋'),
    ('Mango', '芒果', 'fruits', '🥭'),
    ('Kiwi', '猕猴桃', 'fruits', '🥝'),
    ('Pineapple', '菠萝', 'fruits', '🍍'),
    ('Coconut', '椰子', 'fruits', '🥥'),
    ('Papaya', '木瓜', 'fruits', '🍈'),
    ('Avocado', '牛油果', 'fruits', '🥑'),

    # 蔬菜 Vegetables (15)
    ('Tomato', '番茄', 'vegetables', '🍅'),
    ('Potato', '土豆', 'vegetables', '🥔'),
    ('Carrot', '胡萝卜', 'vegetables', '🥕'),
    ('Onion', '洋葱', 'vegetables', '🧅'),
    ('Corn', '玉米', 'vegetables', '🌽'),
    ('Broccoli', '西兰花', 'vegetables', '🥦'),
    ('Cucumber', '黄瓜', 'vegetables', '🥒'),
    ('Pepper', '辣椒', 'vegetables', '🌶️'),
    ('Eggplant', '茄子', 'vegetables', '🍆'),
    ('Cabbage', '卷心菜', 'vegetables', '🥬'),
    ('Lettuce', '生菜', 'vegetables', '🥬'),
    ('Spinach', '菠菜', 'vegetables', '🥗'),
    ('Pumpkin', '南瓜', 'vegetables', '🎃'),
    ('Mushroom', '蘑菇', 'vegetables', '🍄'),
    ('Garlic', '大蒜', 'vegetables', '🧄'),
    ('Ginger', '生姜', 'vegetables', '🫚'),

    # 动物 Animals (25)
    ('Cat', '猫', 'animals', '🐱'),
    ('Dog', '狗', 'animals', '🐶'),
    ('Bird', '鸟', 'animals', '🐦'),
    ('Fish', '鱼', 'animals', '🐟'),
    ('Rabbit', '兔子', 'animals', '🐰'),
    ('Duck', '鸭子', 'animals', '🦆'),
    ('Chicken', '鸡', 'animals', '🐔'),
    ('Cow', '奶牛', 'animals', '🐄'),
    ('Pig', '猪', 'animals', '🐷'),
    ('Horse', '马', 'animals', '🐴'),
    ('Sheep', '羊', 'animals', '🐑'),
    ('Goat', '山羊', 'animals', '🐐'),
    ('Mouse', '老鼠', 'animals', '🐭'),
    ('Elephant', '大象', 'animals', '🐘'),
    ('Lion', '狮子', 'animals', '🦁'),
    ('Tiger', '老虎', 'animals', '🐯'),
    ('Monkey', '猴子', 'animals', '🐵'),
    ('Panda', '熊猫', 'animals', '🐼'),
    ('Bear', '熊', 'animals', '🐻'),
    ('Fox', '狐狸', 'animals', '🦊'),
    ('Wolf', '狼', 'animals', '🐺'),
    ('Deer', '鹿', 'animals', '🦌'),
    ('Zebra', '斑马', 'animals', '🦓'),
    ('Giraffe', '长颈鹿', 'animals', '🦒'),
    ('Kangaroo', '袋鼠', 'animals', '🦘'),
    ('Penguin', '企鹅', 'animals', '🐧'),
    ('Octopus', '章鱼', 'animals', '🐙'),
    ('Butterfly', '蝴蝶', 'animals', '🦋'),
    ('Bee', '蜜蜂', 'animals', '🐝'),

    # 颜色 Colors (12)
    ('Red', '红色', 'colors', '🔴'),
    ('Blue', '蓝色', 'colors', '🔵'),
    ('Green', '绿色', 'colors', '🟢'),
    ('Yellow', '黄色', 'colors', '🟡'),
    ('Orange', '橙色', 'colors', '🟠'),
    ('Purple', '紫色', 'colors', '🟣'),
    ('Pink', '粉色', 'colors', '🩷'),
    ('White', '白色', 'colors', '⚪'),
    ('Black', '黑色', 'colors', '⚫'),
    ('Brown', '棕色', 'colors', '🟤'),
    ('Gray', '灰色', 'colors', '🩶'),
    ('Gold', '金色', 'colors', '🟨'),

    # 家庭 Family (12)
    ('Mom', '妈妈', 'family', '👩'),
    ('Dad', '爸爸', 'family', '👨'),
    ('Baby', '宝宝', 'family', '👶'),
    ('Boy', '男孩', 'family', '👦'),
    ('Girl', '女孩', 'family', '👧'),
    ('Sister', '姐姐/妹妹', 'family', '👫'),
    ('Brother', '哥哥/弟弟', 'family', '👫'),
    ('Grandma', '奶奶', 'family', '👵'),
    ('Grandpa', '爷爷', 'family', '👴'),
    ('Aunt', '阿姨', 'family', '👩‍🦰'),
    ('Uncle', '叔叔', 'family', '👨‍🦰'),
    ('Cousin', '表亲', 'family', '👫'),

    # 学校 School (12)
    ('Book', '书', 'school', '📚'),
    ('Pen', '钢笔', 'school', '🖊️'),
    ('Pencil', '铅笔', 'school', '✏️'),
    ('Bag', '书包', 'school', '🎒'),
    ('Teacher', '老师', 'school', '👨‍🏫'),
    ('School', '学校', 'school', '🏫'),
    ('Desk', '课桌', 'school', '🗂️'),
    ('Chair', '椅子', 'school', '🪑'),
    ('Paper', '纸', 'school', '📄'),
    ('Eraser', '橡皮', 'school', '🧽'),
    ('Ruler', '尺子', 'school', '📏'),
    ('Glue', '胶水', 'school', '🧴'),
    ('Scissors', '剪刀', 'school', '✂️'),

    # 自然 Nature (15)
    ('Sun', '太阳', 'nature', '☀️'),
    ('Moon', '月亮', 'nature', '🌙'),
    ('Star', '星星', 'nature', '⭐'),
    ('Cloud', '云', 'nature', '☁️'),
    ('Rain', '雨', 'nature', '🌧️'),
    ('Snow', '雪', 'nature', '❄️'),
    ('Wind', '风', 'nature', '💨'),
    ('Thunder', '雷', 'nature', '⚡'),
    ('Lightning', '闪电', 'nature', '🌩'),
    ('Tree', '树', 'nature', '🌳'),
    ('Flower', '花', 'nature', '🌸'),
    ('Grass', '草', 'nature', '🌿'),
    ('Mountain', '山', 'nature', '⛰️'),
    ('River', '河', 'nature', '🌊'),
    ('Ocean', '海洋', 'nature', '🌊'),
    ('Rainbow', '彩虹', 'nature', '🌈'),
    ('Forest', '森林', 'nature', '🌲'),

    # 交通工具 Transport (15)
    ('Car', '汽车', 'transport', '🚗'),
    ('Bus', '公交车', 'transport', '🚌'),
    ('Train', '火车', 'transport', '🚂'),
    ('Plane', '飞机', 'transport', '✈️'),
    ('Boat', '船', 'transport', '⛵'),
    ('Bike', '自行车', 'transport', '🚲'),
    ('Motorcycle', '摩托车', 'transport', '🏍️'),
    ('Truck', '卡车', 'transport', '🚚�'),
    ('Taxi', '出租车', 'transport', '🚕'),
    ('Subway', '地铁', 'transport', '🚇'),
    ('Rocket', '火箭', 'transport', '🚀'),
    ('Helicopter', '直升机', 'transport', '🚁'),
    ('Ship', '大船', 'transport', '🚢'),
    'Tram', '有轨电车', 'transport', '🚋'),
    ('Scooter', '滑板车', 'transport', '🛴'),
    ('Ambulance', '救护车', 'transport', '🚑'),

    # 食物 Food (15)
    ('Bread', '面包', 'food', '🍞'),
    ('Rice', '米饭', 'food', '🍚'),
    ('Noodles', '面条', 'food', '🍜'),
    ('Egg', '鸡蛋', 'food', '🥚'),
    ('Milk', '牛奶', 'food', '🥛'),
    ('Cheese', '奶酪', 'food', '🧀'),
    ('Cake', '蛋糕', 'food', '🍰'),
    ('Cookie', '饼干', 'food', '🍪'),
    ('Pizza', '披萨', 'food', '🍕'),
    ('Hamburger', '汉堡', 'food', '🍔'),
    ('Hot dog', '热狗', 'food', '🌭'),
    ('Ice cream', '冰淇淋', 'food', '🍦'),
    ('Candy', '糖果', 'food', '🍬'),
    ('Chocolate', '巧克力', 'food', '🍫'),
    ('Juice', '果汁', 'food', '🧃'),
    ('Sandwich', '三明治', 'food', '🥪'),

    # 身体部位 Body (15)
    ('Head', '头', 'body', '🗣️'),
    ('Face', '脸', 'body', '😊'),
    ('Eye', '眼睛', 'body', '👀️'),
    ('Ear', '耳朵', 'body', '👂'),
    ('Nose', '鼻子', 'body', '👃'),
    ('Mouth', '嘴巴', 'body', '👄'),
    ('Tooth', '牙齿', 'body', '🦷'),
    ('Tongue', '舌头', 'body', '👅'),
    ('Hair', '头发', 'body', '💇'),
    ('Hand', '手', 'body', '🖐️'),
    ('Arm', '手臂', 'body', '💪'),
    ('Finger', '手指', 'body', '👆'),
    'Leg', '腿', 'body', '🦵'),
    ('Foot', '脚', 'body', '🦶'),
    ('Knee', '膝盖', 'body', '🦵'),
    ('Shoulder', '肩膀', 'body', '🤷'),

    # 数字 Numbers (20)
    ('One', '一', 'numbers', '1️⃣'),
    ('Two', '二', 'numbers', '2️⃣'),
    ('Three', '三', 'numbers', '3️⃣'),
    ('Four', '四', 'numbers', '4️⃣'),
    ('Five', '五', 'numbers', '5️⃣'),
    ('Six', '六', 'numbers', '6️⃣'),
    ('Seven', '七', 'numbers', '7️⃣'),
    ('Eight', '八', 'numbers', '8️⃣'),
    ('Nine', '九', 'numbers', '9️⃣'),
    ('Ten', '十', 'numbers', '🔟'),
    ('Eleven', '十一', 'numbers', '1️⃣1️⃣'),
    ('Twelve', '十二', 'numbers', '1️⃣2️⃣'),
    ('Thirteen', '十三', 'numbers', '1️⃣3️⃣'),
    ('Fourteen', '十四', 'numbers', '1️⃣4️⃣'),
    ('Fifteen', '十五', 'numbers', '1️⃣5️⃣'),
    ('Sixteen', '十六', 'numbers', '1️⃣6️⃣'),
    ('Seventeen', '十七', 'numbers', '1️⃣7️⃣'),
    ('Eighteen', '十八', 'numbers', '1️⃣8️⃣'),
    ('Nineteen', '十九', 'numbers', '1️⃣9️⃣'),
    ('Twenty', '二十', 'numbers', '2️⃣'),

    # 服装 Clothes (15)
    ('Hat', '帽子', 'clothes', '🧢'),
    ('Cap', '鸭舌帽', 'clothes', '🧢'),
    ('Shirt', '衬衫', 'clothes', '👕'),
    ('T-shirt', 'T恤', 'clothes', '👕'),
    ('Pants', '裤子', 'clothes', '👖'),
    ('Jeans', '牛仔裤', 'clothes', '👖'),
    ('Dress', '连衣裙', 'clothes', '👗'),
    ('Skirt', '裙子', 'clothes', '👗'),
    ('Coat', '外套', 'clothes', '🧥'),
    ('Jacket', '夹克', 'clothes', '🧥'),
    ('Sweater', '毛衣', 'clothes', '🧶'),
    ('Shoes', '鞋子', 'clothes', '👟'),
    ('Socks', '袜子', 'clothes', '🧦'),
    ('Gloves', '手套', 'clothes', '🧤'),
    ('Scarf', '围巾', 'clothes', '🧣'),
    ('Belt', '皮带', 'clothes', '👔'),

    # 玩具 Toys (10)
    ('Ball', '球', 'toys', '⚽'),
    ('Doll', '洋娃娃', 'toys', '🎎'),
    ('Kite', '风筝', 'toys', '🪁'),
    ('Balloon', '气球', 'toys', '🎈'),
    ('Toy', '玩具', 'toys', '🧸'),
    ('Puzzle', '拼图', 'toys', '🧩'),
    ('Game', '游戏', 'toys', '🎮'),
    ('Drum', '鼓', 'toys', '🥁'),
    ('Trumpet', '喇叭', 'toys', '📯'),
    ('Guitar', '吉他', 'toys', '🎸'),

    # 房子 House (10)
    ('House', '房子', 'house', '🏠'),
    ('Room', '房间', 'house', '🛏️'),
    ('Bed', '床', 'house', '🛏️'),
    ('Chair', '椅子', 'house', '🪑'),
    ('Table', '桌子', 'house', '🪑'),
    ('Window', '窗户', 'house', '🪟'),
    ('Door', '门', 'house', '🚪'),
    ('Roof', '屋顶', 'house', '🏠'),
    ('Floor', '地板', 'house', '🪟'),
    ('Garden', '花园', 'house', '🌻'),

    # 形状 Shapes (8)
    ('Circle', '圆形', 'shapes', '⭕'),
    ('Square', '正方形', 'shapes', '⬜'),
    ('Triangle', '三角形', 'shapes', '🔺'),
    ('Rectangle', '长方形', 'shapes', '▬'),
    ('Star', '星星', 'shapes', '⭐'),
    ('Heart', '心形', 'shapes', '❤️'),
    ('Diamond', '菱形', 'shapes', '💎'),
    ('Oval', '椭圆', 'shapes', '0️⃣'),

    # 方向 Directions (8)
    ('Up', '上', 'directions', '⬆️'),
    ('Down', '下', 'directions', '⬇️'),
    ('Left', '左', 'directions', '⬅️'),
    ('Right', '右', 'directions', '➡️'),
    'Front', '前面', 'directions', '⬆️'),
    ('Back', '后面', 'directions', '⬇️'),
    ('Inside', '里面', 'directions', '🏠'),
    ('Outside', '外面', 'directions', '🌳'),
    ('Middle', '中间', 'directions', '↔️'),

    # 感觉 Feelings (10)
    ('Happy', '快乐', 'feelings', '😊'),
    ('Sad', '伤心', 'feelings', '😢'),
    ('Angry', '生气', 'feelings', '😠'),
    ('Tired', '累', 'feelings', '😴'),
    ('Hungry', '饿', 'feelings', '😋'),
    ('Thirsty', '渴', 'feelings', '🥤'),
    ('Scared', '害怕', 'feelings', '😨'),
    ('Surprised', '惊讶', 'feelings', '😲'),
    ('Excited', '兴奋', 'feelings', '🤩'),
    ('Sick', '生病', 'feelings', '🤒'),
]

# 生成代码
print(f"const ITEMS_DB = [")
for i, (text, zh, topic, emoji) in enumerate(words, 1):
    print(f"  {{ id: 'w{i}', type: 'word', text: '{text}', zh: '{zh}', topic: '{topic}', image: '{emoji}' }},")
print("];")

print(f"\nTotal: {len(words)} words")
